sonar.projectKey=Manajemen_Persuratan
sonar.projectName=Manajemen Persuratan
sonar.token=sqp_9ffc5951ad891f63de328d74530d74288cae7b94
sonar.host.url=http://localhost:9000
sonar.sources=.
sonar.sourceEncoding=UTF-8