<?php

return [
    [
        'key' => 'wilayah_126_129',
        'label' => 'Wilayah (126–129)',
        'items' => [
            ['code' => 126, 'name' => 'Pembagian Wilayah'],
            ['code' => 127, 'name' => 'Penyerahan Wewenang'],
            ['code' => 128, 'name' => 'Perangkat Daerah'],
            ['code' => 129, 'name' => 'Penghapusan/Penggabungan Wilayah/Daerah'],
        ],
    ],
    [
        'key' => 'pemkab_130',
        'label' => 'Pemerintah Kabupaten/Kota (130)',
        'items' => [
            ['code' => 131, 'name' => 'Kepala Daerah TK II'],
            ['code' => 132, 'name' => 'Wakil KDH TK II'],
            ['code' => 133, 'name' => 'Sekwilda TK II/Sekda'],
            ['code' => 134, 'name' => 'Forum Koordinasi Pemerintah di Daerah'],
            ['code' => 135, 'name' => 'Pembentukan/Pemekaran Wilayah'],
            ['code' => 136, 'name' => 'Pembagian Wilayah'],
            ['code' => 137, 'name' => 'Penyerahan urusan/wewenang'],
            ['code' => 138, 'name' => 'Pemerintah Wilayah Kecamatan'],
            ['code' => 139, 'name' => 'Program Pengembangan Kecamatan'],
        ],
    ],
    [
        'key' => 'pemdes_140',
        'label' => 'Pemerintah Desa/Kelurahan (140)',
        'items' => [
            ['code' => 141, 'name' => 'Pamong Desa'],
            ['code' => 142, 'name' => 'Penghasilan Pamong Desa'],
            ['code' => 143, 'name' => 'Kekayaan Desa/Kelurahan'],
            ['code' => 144, 'name' => 'Dewan Tingkat Desa, Dewan Marga'],
            ['code' => 145, 'name' => 'Rembug Desa'],
            ['code' => 146, 'name' => 'Administrasi Desa/Kelurahan'],
            ['code' => 147, 'name' => 'Kewilayahan'],
            ['code' => 148, 'name' => 'Lembaga Tingkat Desa, Badan Perwakilan Desa'],
            ['code' => 149, 'name' => 'Perangkat Desa/Kelurahan'],
            ['code' => 150, 'name' => 'RT, RW, RK, Dusun'],
        ],
    ],
    [
        'key' => 'sosial_463_469',
        'label' => 'Kesejahteraan Sosial (463–469)',
        'items' => [
            ['code' => 463, 'name' => 'Kesejahteraan Anak/Keluarga'],
            ['code' => 464, 'name' => 'Pembinaan Pahlawan'],
            ['code' => 465, 'name' => 'Kesejahteraan Sosial'],
            ['code' => 466, 'name' => 'Sumbangan Sosial'],
            ['code' => 467, 'name' => 'Bimbingan Sosial'],
            ['code' => 468, 'name' => 'PMI'],
            ['code' => 469, 'name' => 'Makam'],
        ],
    ],
    [
        'key' => 'kependudukan_470',
        'label' => 'Kependudukan (470)',
        'items' => [
            ['code' => 471, 'name' => 'Kewarganegaraan Indonesia'],
            ['code' => 472, 'name' => 'Kewarganegaraan Asing'],
            ['code' => 473, 'name' => 'Tidak berkewarganegaraan'],
            ['code' => 474, 'name' => 'Pendaftaran Penduduk'],
            ['code' => 475, 'name' => 'Perpindahan Penduduk'],
            ['code' => 476, 'name' => 'Keluarga Berencana'],
            ['code' => 477, 'name' => 'Catatan Sipil'],
            ['code' => 478, 'name' => 'Akte'],
            ['code' => 479, 'name' => '—'],
        ],
    ],
    [
        'key' => 'media_480',
        'label' => 'Media Massa (480)',
        'items' => [
            ['code' => 481, 'name' => 'Penerbitan, media cetak'],
            ['code' => 482, 'name' => 'Radio'],
            ['code' => 483, 'name' => 'Televisi'],
            ['code' => 484, 'name' => 'Film'],
            ['code' => 485, 'name' => 'Pers'],
            ['code' => 486, 'name' => '—'],
            ['code' => 487, 'name' => 'Penerangan'],
            ['code' => 488, 'name' => 'Operasion room'],
        ],
    ],
];
